export const UPLOAD_FILES = "UPLOAD_FILES";
export const SET_FILE_UPLOADING = "SET_FILE_UPLOADING";
export const SET_FILE_UPLOAD_SUCCESS = "SET_FILE_UPLOAD_SUCCESS";
export const SET_FILE_UPLOAD_FAILED = "SET_FILE_UPLOAD_FAILED";